### ISSUE TITLE
File encodings with base64 data aren't handled correctly

### ISSUE THREAD

**Issue by crawford** [coreos/coreos-cloudinit#296]
The YAML parser appears to be silently decoding base64 data. If the user explictly declares the data to be base64, it's run through the decoder a second time causing a failure.

**Comment by crawford** [comment]
These are equivalent.
```yaml
write_files:
 - path: /tmp/base64
    content: SGVsbG8hCg==
    encoding: base64

  - path: /tmp/base64.norm
    content: !!binary SGVsbG8hCg==
```
