### ISSUE TITLE
hostname and machine-id for etcd section

### ISSUE THREAD

**Issue by polvi** [coreos/coreos-cloudinit#30]
$hostname and $machine_id should be a valid substitutions for the etcd section. coreos.etcd.name should default to $hostname unless specificed. Cloudinit should make sure it runs its own hostname code early so that value will apply. $hostname should be the same as the result of the hostname() system call. $machine-id should be the value in /etc/machine-id.

**Comment by crawford** [comment]
@polvi do you still want this feature (one year later...)? The hostname substitution is going to be racy, but machine_id might be useful (though I haven't heard anyone else ask for it).

**Comment by chansn** [comment]
if its for etcd, then %H will work, as it gets resolved by systemd. We use it here for a generic cloud-init. Only slight annoyance is that the new etcd 2.0 params are ignored, so we just feed them to an extra unit file under etcd.service.

Example:
``` yaml
#cloud-config

coreos:
  etcd:
    name: "%H"
    data-dir: /var/etcd/data
  fleet:
    etcd-servers: http://%H:2379
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
write_files:
  - path: /run/systemd/system/etcd.service.d/10-param.conf
    permissions: 0644
    content: |
      [Service]
      Environment=ETCD_ADVERTISE_CLIENT_URLS=http://%H:2379
      Environment=ETCD_LISTEN_CLIENT_URLS=http://%H:2379
      Environment=ETCD_LISTEN_PEER_URLS=http://%H:2380
```
