### ISSUE TITLE
Impossible to login with SSH

### ISSUE THREAD

**Issue by AlexanderShniperson** [coreos/coreos-cloudinit#302]
Hello.
I wrote my cloud-config that set SSH port and keys for users, but i cant login with SSH key anyway, 
the server prompts me enter some password.

what went wrong?

here is my config file:
```
#cloud-config

hostname: CoreOS01

users:
  - name: core
    # Password: password
    passwd: $6$Z7TyN/ZtOHm/O$6JYggxF6fxh3epWjItfdQLJNzjoCAOdXUsfOyQ1QflAEIimY5ZeyB2Ha2YW.TCztz.1BtPHYujiH4Js4tXES.1
  - name: camka
    # Password: password
    passwd: $6$Z7TyN/ZtOHm/O$6JYggxF6fxh3epWjItfdQLJNzjoCAOdXUsfOyQ1QflAEIimY5ZeyB2Ha2YW.TCztz.1BtPHYujiH4Js4tXES.1
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCai45XB6SDrfRspSZTtkJoPsmBecIoLOveMpDJf5n25x/yo4ZH0EzlGZrCZkJfA8rqgiXGmp6kaaQ7rgN+E1KN43lkSKByrzfCrnfNAhgQrIsYYk2GdL1YxV9PL2zaCLu/uT+6/2gQIHyZ7RM5tQLVw1f7Kcug0LZafU7HN3LpPk13AtsmTqfphxXk/AfYSuTq2qqjOwZyjx3tj6D5pme8CmZySmcGUXJN423A3AsvVY6oIb/GuOldSkwp7XZKhta6M72R0pogmWeKPDZd5JYNx6IZLebHfII3/j5iVPBJwhnVo1VG39gHUjZOUbR+Lg8FcKTGB2tWLbWaowXT6TYB camkadev@Mac-mini-Aleksandr.local

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCai45XB6SDrfRspSZTtkJoPsmBecIoLOveMpDJf5n25x/yo4ZH0EzlGZrCZkJfA8rqgiXGmp6kaaQ7rgN+E1KN43lkSKByrzfCrnfNAhgQrIsYYk2GdL1YxV9PL2zaCLu/uT+6/2gQIHyZ7RM5tQLVw1f7Kcug0LZafU7HN3LpPk13AtsmTqfphxXk/AfYSuTq2qqjOwZyjx3tj6D5pme8CmZySmcGUXJN423A3AsvVY6oIb/GuOldSkwp7XZKhta6M72R0pogmWeKPDZd5JYNx6IZLebHfII3/j5iVPBJwhnVo1VG39gHUjZOUbR+Lg8FcKTGB2tWLbWaowXT6TYB camkadev@Mac-mini-Aleksandr.local

write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp
      PermitRootLogin no
      AllowUsers core camka
      PasswordAuthentication no
      ChallengeResponseAuthentication no

coreos:
  etcd:
      name: coreosnode001
      discovery: https://discovery.etcd.io/6a991fe781b0dc9ce27457879bfb7ab1
  units:
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2211
        Accept=yes
```
