### ISSUE TITLE
Disable a unit without masking it

### ISSUE THREAD

**Issue by wmark** [coreos/coreos-cloudinit#311]
I will use ```sshd.socket``` as example:

The default one which comes with CoreOS listens on ```0.0.0.0:22```. I'd like to replace it by a ```sshd.socket``` that is limited to ```$public_ipv4:22``` (one IP address).

1. Just installing and *restart*ing a new unit file with the same name (see below) results in the error ```Address already in use```.

2. The *command* "disable" doesn't exist. Therefore I currently cannot do this:
```yaml
    - name: sshd.socket
      command: disable
    - name: sshd.socket
      command: restart
      runtime: true
      content: |
        [Unit]
        Description=OpenSSH Server Socket
        Conflicts=sshd.service

        [Socket]
        ListenStream=$public_ipv4:22
        FreeBind=true
        Accept=yes

        [Install]
        WantedBy=sockets.target
```

What's the best way to achieve the desired result, as described in the second paragraph? Will it work on the first, second, and third restart?

----
See also:
 * coreos/docs#422
 * coreos/bugs#57

----
A workaround for this special exemplary case is to add a delay. This is due to the old socket lingering around for some seconds after having been closed (due to the old ```sshd.socket``` having been stopped), which denies you the new ```xyz:22```. If it were not for the new address you could use ```ReusePort=true``` to fix that. — Here's the delay, which doesn't address the intention of this *issue*, though:
```yaml
        …
        [Socket]
        ExecStartPre=/usr/bin/sleep 30
        ListenStream=$public_ipv4:22
        …
```

EDIT: Removed listening on IPv6, which didn't make any difference.

**Comment by crawford** [comment]
The command you are looking for is `stop`. Though I don't believe that will immediately tear down the socket.

I can partially reproduce you issue with the following config:

```yaml
    - name: sshd.socket
      command: restart
      runtime: true
      drop-ins:
        - name: addr.conf
          content: |
            [Socket]
            ListenStream=
            ListenStream=$public_ipv4:22
            ListenStream=[::]:22
            BindIPv6Only=ipv6-only
            FreeBind=true
```

I do see `systemd[1]: Failed to reload: Address already in use`, but the socket is correctly restarted. I've verified that I can still ssh properly and netstat shows:

```
core@crawford-test-1 ~ $ netstat -ln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 $public_ipv4:22         0.0.0.0:*               LISTEN     
```

I'm going to dig into this a bit more, but could you tell me your version of systemd and the cloud provider you are using?
