### ISSUE TITLE
Higher level abstraction for defining units

### ISSUE THREAD

**Issue by errordeveloper** [coreos/coreos-cloudinit#312]
I think it could help validator if instead of writing:
```yaml
  - name: weave-network.target
    command: start
    enable: true
    content: |
      [Unit]
      Requires=weave.service
      RefuseManualStart=no
      Wants=weave.service
      [Install]
      WantedBy=multi-user.target
```

I could write:
```yaml
  - name: weave-network.target
    command: start
    enable: true
    unit:
      Requires: [ "weave.service" ]
      RefuseManualStart: no
      Wants: [ "weave.service" ]
    install:
      WantedBy: [ "multi-user.target" ]
```

**Comment by errordeveloper** [comment]
Also, I'm never too sure of whether environment files need double or single quoting, so that would a bonus to wrap environment file as well...

**Comment by errordeveloper** [comment]
Pinging @kelseyhightower.

**Comment by crawford** [comment]
The validator doesn't inspect the contents of unit files. `systemd-analyze verify` can help with that.

**Comment by errordeveloper** [comment]
Sure, but having some basic validation would be nice... I spoke with @kelseyhightower, this was for the purpose of writing down the idea.

**Comment by crawford** [comment]
It _would_ be interesting if we piped the systemd units into `systemd-analyze verify` and showed that output as well. I think that would be enough to address your concerns, right?

**Comment by errordeveloper** [comment]
> It would be interesting if we piped the systemd units into systemd-analyze verify and showed that output as well.

If this is doable in the validator, then it'd be great to have.

> I think that would be enough to address your concerns, right?

Initially, I was more concerned about safety of the unit contents, avoiding simple typos in key names, missing required keys and syntax in the values passed in (e.g. whether `;` are used as intended or someone tries to pass a command to `/bin/sh -c` and forgot to quote it, may be that would require a shell helper, which would be very nice too).

But then also, it's way easier to write pure YAML, then a hybrid of YAML+INI.

**Comment by errordeveloper** [comment]
> Also, I'm never too sure of whether environment files need double or single quoting, so that would a bonus to wrap environment file as well...

Something like:

```yaml
environment_files:
    - name: /etc/foo.env
      KEY: value
```

Would produce a file with correct quoting, and can also be used programatically for validation.

If I did:
```
 - name: foo.target
    command: start
    enable: true
    service:
      EnvironmentFileIfPresent: /etc/global.env # =>  EnvironmentFile=-/etc/global.env
      EnvironmentFile: /etc/bar.env
```

And forgot to specify `/etc/bar.env`, I could see an error before getting the target box to boot.

Also, systemd doesn't let you know about undefined variables (well, sort of just like shell does)... But it also doesn't see to output their values in `systemctl status <unit>`, which I find a problem.

I understand that there is quite a lot of stuff that I'm trying to suggest, and it might be getting into "systemd unit compiler" territory, but I wanted to make sure to share my experience and what I think would help novice users in the future. I originally commented in #221, but after chatting with @kelseyhightower, I figured this is a bigger subject.
