### ISSUE TITLE
validator shows incorrect line number for invalid file contents

### ISSUE THREAD

**Issue by crawford** [coreos/coreos-cloudinit#323]
```yaml
#cloud-config
write_files:
  - encoding: gzip
    content: !!binary |
      abc
```

```
bin/coreos-cloudinit --validate --from-file a
Checking availability of "local-file"
Fetching user-data from datasource of type "local-file"
line 1: error: !!binary value contains invalid base64 data
line 0: warning: incorrect type for "" (want struct)
```
