### ISSUE TITLE
Environment substitution for cloud-config

### ISSUE THREAD

**Issue by ForbiddenEra** [coreos/coreos-cloudinit#325]
I was trying to do something along the lines of..

```
fleet:
public-ip: \$private_ipv4 # used for fleetctl ssh command
metadata: bandwidth_limit=$BANDWIDTH_LIMIT,cpus=$PROCESSORS,host=$HOSTNAME,memory=$MEMORY,provider=$PROVIDER,region=$REGION,storage_size=$INTERNAL_STORAGE,storage_type=$INTERNAL_STORAGE_TYPE,role=$ROLE,block_storage_size=$BLOCK_STORAGE_SIZE,block_storage_type=$BLOCK_STORAGE_TYPE
```

With a "double init" where I init a basic system, run scripts to define all those variables, and then re-init with my real cloud-config..

I thought I could simply put them in /etc/environment and include that with my unit?

```
[Unit]
Description=Run coreos-cloudinit with actual cloud-config after environment has been set up
Requires=setup-environment.service
After=setup-environment.service

[Service]
Type=oneshot
RemainAfterExit=yes
EnvironmentFile=/etc/environment
ExecStop=/usr/bin/true
ExecStart=/usr/bin/coreos-cloudinit --from-file=/opt/cloud-config.yml 
```

I'm guessing systemd doesn't do this (Kinda doing what's mentioned in https://github.com/coreos/coreos-cloudinit/issues/205 - the double init)

As a work around for now, I can have my scripts that set those variables push them to the cloud-init..

**Comment by crawford** [comment]
I think the variable names will be wrong. /etc/environment uses "COREOS_{PUBLIC,PRIVATE}_IPV4", but you are using "$private_ipv4" in your service (`systemctl cat fleet.service` will show the drop-in that coreos-cloudinit generates). I think this is what you want:

```yaml
  fleet:
    public-ip: $COREOS_PUBLIC_IPV4 # used for fleetctl ssh command
    metadata: bandwidth_limit=$BANDWIDTH_LIMIT,cpus=$PROCESSORS,host=$HOSTNAME,memory=$MEMORY,provider=$PROVIDER,region=$REGION,storage_size=$INTERNAL_STORAGE,storage_type=$INTERNAL_STORAGE_TYPE,role=$ROLE,block_storage_size=$BLOCK_STORAGE_SIZE,block_storage_type=$BLOCK_STORAGE_TYPE
```

You shouldn't need to escape the variable because we don't do variable expansion sanely. The variable is only replaced if it exists (and this one doesn't).
