### ISSUE TITLE
docker private registry

### ISSUE THREAD

**Issue by vallard** [coreos/coreos-cloudinit#342]
Sorry if this has been answered before or if I'm asking in the wrong place.  I can't find the right way to solve this.  I'm using cloud-init exactly like shown in the demo: https://coreos.com/docs/launching-containers/building/registry-authentication/

```yaml
#cloud-config

write_files:
  - path: /etc/systemd/system/docker.service.d/50-insecure-registry.conf
    content: |
        [Service]
        Environment='DOCKER_OPTS=--insecure-registry="10.0.0.0/8"'
```
My private registry is 10.2.3.7:5000.  

Once this machine boots I do the following: 
```
docker pull cirros
docker tag cirros 10.2.3.7:5000/vallard/cirros
docker push 10.2.3.7:5000/vallard/cirros
```
(Note: This registry is a container running in another coreos instance that has never been accessed)

I get the error: 
```
FATA[0004] Error: v1 ping attempt failed with error: Get https://10.2.3.7:5000/v1/_ping: EOF. If this private registry supports only HTTP or HTTPS with an unknown CA certificate, please add `--insecure-registry 10.2.3.7:5000` to the daemon's arguments. In the case of HTTPS, if you have access to the registry's CA certificate, no need for the flag; simply place the CA certificate at /etc/docker/certs.d/10.2.3.7:5000/ca.crt 
```
It doesn't seem to be falling back to http for some reason.  Doing:

```
curl http://10.2.3.7:5000/v1/_ping
```
returns {} like its supposed to.  

Also, it did create the file in /etc/systemd/system/docker.service.d/50-insecure-registry.conf

Hopefully I'm missing something really simple.  Thanks for any help!

**Comment by vallard** [comment]
figured it out.  Cloud-init was incorrect.  Was writing the file but wasn't restarting the daemon. 
The below worked:
```
coreos:
  units:
    - name: docker.service
      drop-ins: 
        - name: 50-insecure-registry.conf
          content: |
            [Service]
            Environment='DOCKER_OPTS=--insecure-registry=ci:5000 '
```
