### ISSUE TITLE
Can't login to Coreos under Virtualbox

### ISSUE THREAD

**Issue by DJviolin** [coreos/coreos-cloudinit#358]
I followed this tutorial:
https://coreos.com/docs/running-coreos/platforms/virtualbox/

This is my user-data file in `[config-2.iso]/openstack/latest/` directory:

```yaml
#cloud-config

coreos:
  etcd:
    # generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/vtv45w....54tvt457575
    addr: $public_ipv4:4001
    peer-addr: $public_ipv4:7001
  etcd2:
    #generate a new token for each unique cluster from https://discovery.etcd.io/new
    discovery: https://discovery.etcd.io/vtv45w....54tvt457575
    # multi-region and multi-cloud deployments need to use $public_ipv4
    advertise-client-urls: http://$public_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    # listen on both the official ports and the legacy ports
    # legacy ports can be omitted if your application doesn't depend on them
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380 #,http://$private_ipv4:7001
  fleet:
    public-ip: $public_ipv4 # used for fleetctl ssh command
    metadata: region=europe,public_ip=$public_ipv4
  flannel:
    interface: $public_ipv4
  update:
    reboot-strategy: best-effort
  units:
    #- name: etcd.service
    #  command: start
    # To use etcd2, comment out the above service and uncomment these
    # Note: this requires a release that contains etcd2
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
    - name: sshd.socket
      command: restart
      content: |
        [Socket]
        ListenStream=2222
        Accept=yes
write_files:
  - path: /etc/ssh/sshd_config
    permissions: 0600
    owner: root:root
    content: |
      # Use most defaults for sshd configuration.
      UsePrivilegeSeparation sandbox
      Subsystem sftp internal-sftp

      PermitRootLogin no
      AllowUsers core lanti
      PasswordAuthentication no
      ChallengeResponseAuthentication no
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1.......
hostname: coreos0001
users:
- name: lanti
  passwd: password
  groups:
    - sudo
    - docker
  ssh-authorized-keys:
    - ssh-rsa AAAAB3NzaC1.......
#manage_etc_hosts: localhost

```

This is my CoreOS welcome screen:

![coreos-vdi](https://cloud.githubusercontent.com/assets/5021728/8639741/fa432a3c-28e2-11e5-881a-9a76135bae1a.png)

I just can't SSH in from windows. Port 8081 forwarded to 22:

```shell
$ ssh lanti@127.0.0.1 -p 8081 -i ~/.ssh/id_rsa
$ ssh lanti@127.0.0.1 -p 2222 -i ~/.ssh/id_rsa
$ ssh core@127.0.0.1 -p 8081 -i ~/.ssh/id_rsa
$ ssh lanti@192.168.1.6
$ ssh lanti@10.0.2.15
```
I tried every combinations of these.

I creating the iso with this command:

```shell
$ mkisofs -R -V config-2 -o D:/VM/coreos-vdi-creator/config-2.iso D:/VM/cloud-config
```
